
services:
  backend:
    build:
      context: ./backend/laravel
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:80"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: hotel_reservation
      DB_USERNAME: root
      DB_PASSWORD: password
    volumes:
      - ./backend/laravel:/var/www/html
      - /var/www/html/vendor
    networks:
      - webapp
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    networks:
      - webapp
    environment: 
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: hotel_reservation
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
    - CHOKIDAR_USEPOLLING=true
    ports:
      - "4300:80"
    networks:
      - webapp
    depends_on:
      - backend

networks:
  webapp:
    driver: bridge

volumes:
  mysql_data:
