services:
  backend:
    image: taha7486/hotel-backend:v3
    #build:
      #context: ./backend/laravel
      #dockerfile: Dockerfile
    container_name: backend 
    ports:
      - "8000:80"
    volumes:
      - ./backend/laravel:/var/www/html 
      - vendor_data:/var/www/html/vendor
    depends_on:
      - mysql
    networks:
      - webapp
      
  frontend:
    image: taha7486/hotel-frontend:latest
    #build:
      #context: ./frontend
      #dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4300:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - webapp

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: hotel_reservation
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webapp
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql  
      PMA_PORT: 3306
    ports:
      - "8080:80" 
    depends_on:
      - mysql
    networks:
      - webapp 
networks:
  webapp:
    driver: bridge

volumes:
  db_data:
  vendor_data: