name: Build and Publish image to Docker Hub

on: 
  workflow_dispatch:

jobs:
  publish_images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image (backend)
      run: docker build ./api/ -t taha7486/backend:latest

    - name: Push Docker image (backend)
      run: docker push taha7486/backend:latest
