name: Build and Publish Docker Image

on: 
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['backend/laravel/**']  # Updated to watch the correct folder

jobs:
  publish_images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Key change: Path updated to ./backend/laravel/
    - name: Build Docker image (backend)
      run: docker build ./backend/laravel/ -t taha7486/hotel-backend:v2

    - name: Push Docker image (backend)
      run: docker push taha7486/hotel-backend:v2