name: Build Backend Image

on:
  push:
    branches: [main]
    paths:
      - 'backend/laravel/**'

jobs:
  build_backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        context: ./backend/laravel
        push: true
        tags: taha7486/hotel-backend:latest
