name: Build MySQL Image

on:
  push:
    branches: [main]
    paths:
      - 'mysql/**'

jobs:
  build_mysql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build MySQL Docker image
      run: docker build ./mysql/ -t taha7486/hotel-mysql:latest

    - name: Push MySQL Docker image
      run: docker push taha7486/hotel-mysql:latest
